---
apiVersion: v1
kind: Service
metadata:
  name: node # naming the deployment
  namespace: default

# Specifications to include ports 
spec:
  ports:
    - nodePort: 30001 # a range is 30000-32768
      port: 3000
      protocol: TCP
      targetPort: 3000
     # name: grpc


# let define the selector and label to connect to nginx deployment
  selector:
    app: node # this label connects this service to deployment

# creating Loadbalancer type of deployment
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  selector:
    app: node
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer