---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment # naming the deployment

spec:
  selector:
    matchLabels:
      app: node # look for this label to match this k8 service


  replicas: 3

  template:
    metadata:
      labels:
        app: node

    spec:
      containers:
      - name: node
        image: rocky11/node-app:new
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mongodb://10.107.114.138:27017/posts
      #imagePullPolicy: Always